---
language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - cd raise_utils/transforms && cythonize -i -a remove_labels.pyx
  - cd tests && ./test.sh
  - bash <(curl -s https://codecov.io/bash)
