coverage:
  status:
    project:
      default:
        target: 80%  # the required coverage

    patch:
        default:
            target: 85%  # new code coverage

    changes:
        default:
            target: 0%  # change in coverage?
